# Generated by Django 4.1 on 2023-07-18 09:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name_en", models.CharField(blank=True, max_length=500, null=True)),
                ("name_ne", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "road_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Black_topped", "Black_topped"),
                            ("Gravel", "Gravel"),
                            ("Concrete", "Concrete"),
                            ("Earthen", "Earthen"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "road_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Major", "Major"),
                            ("Minor", "Minor"),
                            ("Subsidiary", "Subsidiary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ward_no", models.IntegerField(blank=True, null=True)),
                (
                    "start_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "end_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Shapefile", "Shapefile"),
                            ("CSV", "CSV"),
                            ("Geojson", "Geojson"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="Files"),
                ),
                ("attr_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4236
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "gate_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("house_no", models.IntegerField(blank=True, null=True)),
                ("tole_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "building_plan",
                    models.ImageField(blank=True, null=True, upload_to="Files/images"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Shapefile", "Shapefile"),
                            ("CSV", "CSV"),
                            ("Geojson", "Geojson"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="Files"),
                ),
                ("bbox", models.JSONField(blank=True, default=dict, null=True)),
                ("attr_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4236
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
