# Generated by Django 4.1 on 2023-07-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="ward_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="road",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("Shapefile", "shapefile"),
                    ("CSV", "csv"),
                    ("Geojson", "geojson"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Major", "major"),
                    ("Minor", "minor"),
                    ("Subsidiary", "subsidiary"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Black_topped", "black_topped"),
                    ("Gravel", "gravel"),
                    ("Concrete", "concrete"),
                    ("Earthen", "earthen"),
                    ("Others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
