# Generated by Django 4.1 on 2023-07-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_building_association_type_building_roof_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="lat_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="long_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="lat_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="long_field",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
