# Generated by Django 4.1 on 2023-07-24 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_building_lat_field_building_long_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R.C.C", "R.C.C"),
                    ("Load Bearing", "Load Bearing"),
                    ("Wood/Bamboo", "Wood/Bamboo"),
                    ("Mud Block", "Mud Block"),
                    ("Others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="building_use",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Hospitality", "Hospitality"),
                        ("SMES", "SMES"),
                        ("Retails", "Retails"),
                        ("CNE", "CNE"),
                        ("Agriculture", "Agriculture"),
                        ("Educational", "Educational"),
                        ("Health", "Health"),
                        ("Financial", "Financial"),
                        ("Religious", "Religious"),
                        ("No Use", "No Use"),
                        ("Other", "Other"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                null=True,
                size=10,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("Left", "Left"), ("Right", "Right")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="metric_address",
            field=models.CharField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="owner_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Registered and completed", "Registered and completed"),
                    (
                        "Registered but building under construction",
                        "Registered but building under construction",
                    ),
                    ("Not registered", "Not registered"),
                    ("Archived", "Archived"),
                    ("Others", "Others"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
    ]
