# Generated by Django 4.1 on 2023-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_building_building_structure_building_building_use_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_use",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hospitality", "Hospitality"),
                    ("SMES", "SMES"),
                    ("Retails", "Retails"),
                    ("CNE", "CNE"),
                    ("Agriculture", "Agriculture"),
                    ("Educational", "Educational"),
                    ("Health", "Health"),
                    ("Financial", "Financial"),
                    ("Religious", "Religious"),
                    ("No Use", "No Use"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
