# Generated by Django 4.1 on 2023-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_building_building_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="association_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main", "main"),
                    ("associate", "associate"),
                    ("dissociate", "dissociate"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R.C.C", "R.C.C"),
                    ("framed", "framed"),
                    ("Load Bearing", "Load Bearing"),
                    ("Wood/Bamboo", "Wood/Bamboo"),
                    ("compressed_mud", "compressed_mud"),
                    ("Mud Block", "Mud Block"),
                    ("Others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_use",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hospitality", "hospitality"),
                    ("SMES", "smes"),
                    ("Retails", "retails"),
                    ("residential", "residential"),
                    ("institutional", "institutional"),
                    ("CNE", "cne"),
                    ("mixed", "mixed"),
                    ("Agriculture", "agriculture"),
                    ("Educational", "educational"),
                    ("Health", "health"),
                    ("Financial", "financial"),
                    ("Religious", "religious"),
                    ("unused", "unused"),
                    ("Other", "other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Registered and completed", "Registered and completed"),
                    (
                        "Registered but building under construction",
                        "Registered but building under construction",
                    ),
                    ("Not registered", "Not registered"),
                    ("Archived", "archived"),
                    ("Others", "Others"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "rcc"),
                    ("tile", "tile"),
                    ("cgi-sheet", "cgi-sheet"),
                    ("others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black_topped", "black_topped"),
                    ("gravel", "gravel"),
                    ("concrete", "concrete"),
                    ("unpaved", "unpaved"),
                    ("Earthen", "earthen"),
                    ("Others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
