# Generated by Django 4.1 on 2023-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_building_association_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="road_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National Highway", "national_highway"),
                    ("Feeder Road", "feeder_road"),
                    ("District Road", "district_Road"),
                    ("Arterial Road", "arterial_Road"),
                    ("Sub-arterial Road", "sub_arterial_road"),
                    ("collector_road", "collector_road"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
