# Generated by Django 4.1 on 2023-07-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_road_road_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("Shapefile", "shapefile"),
                    ("CSV", "csv"),
                    ("Geojson", "geojson"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
