# Generated by Django 4.1 on 2023-07-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_building_geom_remove_road_geom_roadgeometry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildinggeometry",
            name="feature",
        ),
        migrations.AddField(
            model_name="building",
            name="feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building",
                to="core.buildinggeometry",
            ),
        ),
    ]
