# Generated by Django 4.1 on 2023-07-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_buildinggeometry_feature_building_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roadgeometry",
            name="feature",
        ),
        migrations.AddField(
            model_name="road",
            name="feature",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="road_geometry",
                to="core.roadgeometry",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_geometry",
                to="core.buildinggeometry",
            ),
        ),
    ]
