# Generated by Django 4.1 on 2023-07-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_roadgeometry_feature_road_feature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="feature",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_geometry",
                to="core.buildinggeometry",
            ),
        ),
    ]
