# Generated by Django 4.1 on 2023-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_building_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Shapefile", "shapefile"),
                            ("CSV", "csv"),
                            ("Geojson", "geojson"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("file_upload", models.FileField(upload_to="Files")),
            ],
        ),
        migrations.CreateModel(
            name="RoadUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Shapefile", "shapefile"),
                            ("CSV", "csv"),
                            ("Geojson", "geojson"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("file_upload", models.FileField(upload_to="Files")),
            ],
        ),
    ]
