# Generated by Django 4.1 on 2023-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_buildingupload_roadupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National Highway", "national_highway"),
                    ("Feeder Road", "feeder_road"),
                    ("District Road", "district_road"),
                    ("Other_Urban_Road", "other_urban_road"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black_topped", "black_topped"),
                    ("gravel", "gravel"),
                    ("concrete", "concrete"),
                    ("Earthen", "earthen"),
                    ("Others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
