# Generated by Django 4.1 on 2023-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_building_file_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "rcc"),
                    ("framed", "framed"),
                    ("load_Bearing", "load_bearing"),
                    ("wood/bamboo", "wood/bamboo"),
                    ("compressed_mud", "compressed_mud"),
                    ("mud_block", "mud_block"),
                    ("others", "others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_use",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hospitality", "hospitality"),
                    ("smes", "smes"),
                    ("retails", "retails"),
                    ("residential", "residential"),
                    ("institutional", "institutional"),
                    ("cne", "cne"),
                    ("mixed", "mixed"),
                    ("agriculture", "agriculture"),
                    ("educational", "educational"),
                    ("health", "health"),
                    ("financial", "financial"),
                    ("religious", "religious"),
                    ("unused", "unused"),
                    ("Other", "other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered_and_completed", "registered_and_completed"),
                    (
                        "registered but building under construction",
                        "registered but building under construction",
                    ),
                    ("not_registered", "not_registered"),
                    ("archived", "archived"),
                    ("others", "others"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
    ]
