# Generated by Django 4.1 on 2023-07-28 09:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0018_alter_building_building_structure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PalikaGeometry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.FloatField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PalikaGeometryFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("Palika", "palika"), ("Ward", "ward")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("file_upload", models.FileField(upload_to="palika")),
            ],
        ),
        migrations.CreateModel(
            name="PalikaWardGeometry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward_no", models.IntegerField(blank=True, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PalikaProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("name_ne", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "description_ne",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "logo_en",
                    models.ImageField(blank=True, null=True, upload_to="palika_logo/"),
                ),
                (
                    "logo_ne",
                    models.ImageField(blank=True, null=True, upload_to="palika_logo/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
