# Generated by Django 4.1 on 2023-07-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_palikageometry_palikageometryfile_palikawardgeometry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="palikawardgeometry",
            name="numbering_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Completed", "completed"),
                    ("Ongoing", "ongoing"),
                    ("Not Started", "not_started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
