# Generated by Django 4.1 on 2023-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_palikawardgeometry_numbering_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("left", "left"), ("right", "right")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("major", "major"),
                    ("minor", "minor"),
                    ("subsidiary", "subsidiary"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national_highway", "national_highway"),
                    ("feeder_road", "feeder_road"),
                    ("district_road", "district_road"),
                    ("other_urban_road", "other_urban_road"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black_topped", "black_topped"),
                    ("gravel", "gravel"),
                    ("concrete", "concrete"),
                    ("earthen", "earthen"),
                    ("unpaved", "unpaved"),
                    ("others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
