# Generated by Django 4.1 on 2023-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_building_direction_alter_road_road_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered_and_completed", "registered_and_completed"),
                    (
                        "registered_but_building_under_construction",
                        "registered_but_building_under_construction",
                    ),
                    ("not_registered", "not_registered"),
                    ("archived", "archived"),
                    ("others", "others"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
    ]
