# Generated by Django 4.1 on 2023-07-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_building_reg_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="road",
            old_name="name_en",
            new_name="road_name_en",
        ),
        migrations.RenameField(
            model_name="road",
            old_name="name_ne",
            new_name="road_name_ne",
        ),
        migrations.AddField(
            model_name="road",
            name="road_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
