# Generated by Django 4.1 on 2023-08-01 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_physicalinstallation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physicalinstallation",
            name="building",
        ),
    ]
