# Generated by Django 4.1 on 2023-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_physicalinstallation_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="road_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
