# Generated by Django 4.1 on 2023-08-03 08:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0026_building_road_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="owner_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("governmental", "governmental"),
                    ("non_governmental", "non_governmental"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="temprorary_type",
            field=models.CharField(
                blank=True,
                choices=[("permanent", "permanent"), ("temporary", "temporary")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "rcc"),
                    ("framed", "framed"),
                    ("load_Bearing", "load_bearing"),
                    ("earthen_masonry", "earthen_masonry"),
                    ("wood/bamboo", "wood/bamboo"),
                    ("compressed_mud", "compressed_mud"),
                    ("mud_block", "mud_block"),
                    ("others", "others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_use",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "residential"),
                    ("commercial", "commercial"),
                    ("multi_use", "multi_use"),
                    ("institutional", "institutional"),
                    ("unused", "unused"),
                    ("Other", "other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered_and_completed", "registered_and_completed"),
                    (
                        "registered_and_under_construction",
                        "registered_and_under_construction",
                    ),
                    ("not_registered", "not_registered"),
                    ("not_aware", "not_aware"),
                    ("archived", "archived"),
                    ("others", "others"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "rcc"),
                    ("tile", "tile"),
                    ("cgi-sheet", "cgi-sheet"),
                    ("timber", "timber"),
                    ("straw", "straw"),
                    ("others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="VectorLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="Files"),
                ),
                (
                    "lat_field",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                (
                    "long_field",
                    models.CharField(blank=True, default="", max_length=250, null=True),
                ),
                ("bbox", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "geometry_type",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("attr_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4236
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vector_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature",
                        to="core.vectorlayer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
