# Generated by Django 4.1 on 2023-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_building_owner_status_building_temprorary_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="building_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "rcc"),
                    ("framed", "framed"),
                    ("load_bearing", "load_bearing"),
                    ("timber", "timber"),
                    ("earthen_masonry", "earthen_masonry"),
                    ("wood/bamboo", "wood/bamboo"),
                    ("compressed_mud", "compressed_mud"),
                    ("mud_block", "mud_block"),
                    ("other", "other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
