# Generated by Django 4.1 on 2023-08-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_building_building_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "rcc"),
                    ("tile", "tile"),
                    ("cgi-sheet", "cgi-sheet"),
                    ("straw", "straw"),
                    ("others", "others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
