# Generated by Django 4.1 on 2023-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_building_roof_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="association_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("main", "Main"),
                    ("associate", "Associate"),
                    ("dissociate", "Dissociate"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "RCC"),
                    ("framed", "Framed"),
                    ("load_bearing", "Load bearing"),
                    ("timber", "Timber"),
                    ("earthen_masonry", "Earthen masonry"),
                    ("wood/bamboo", "Wood/Bamboo"),
                    ("compressed_mud", "Compressed mud"),
                    ("mud_block", "Mud block"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_use",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("multi_use", "Multi use"),
                    ("institutional", "Institutional"),
                    ("unused", "Unused"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="owner_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("governmental", "Governmental"),
                    ("non_governmental", "Non governmental"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered_and_completed", "Registered and completed"),
                    (
                        "registered_and_under_construction",
                        "Registered and under construction",
                    ),
                    ("not_registered", "Not registered"),
                    ("not_aware", "Not aware"),
                    ("archived", "Archived"),
                    ("others", "Others"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "RCC"),
                    ("tile", "Tile"),
                    ("cgi-sheet", "CGI sheet"),
                    ("straw", "Straw"),
                    ("others", "Others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="temprorary_type",
            field=models.CharField(
                blank=True,
                choices=[("permanent", "Permanent"), ("temporary", "Temporary")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildingupload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("shapefile", "Shapefile"),
                    ("csv", "CSV"),
                    ("geojson", "Geojson"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="palikageometryfile",
            name="file_type",
            field=models.CharField(
                choices=[("palika", "Palika"), ("ward", "Ward")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="palikawardgeometry",
            name="numbering_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("completed", "Completed"),
                    ("ongoing", "Ongoing"),
                    ("not_started", "Not Started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("major", "Major"),
                    ("minor", "Minor"),
                    ("subsidiary", "Subsidiary"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national_highway", "National highway"),
                    ("feeder_road", "Feeder road"),
                    ("district_road", "District road"),
                    ("other_urban_road", "Other urban road"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black_topped", "Black Topped"),
                    ("gravel", "Gravel"),
                    ("concrete", "Concrete"),
                    ("earthen", "Earthen"),
                    ("unpaved", "Unpaved"),
                    ("others", "Others"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="roadupload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("shapefile", "Shapefile"),
                    ("csv", "CSV"),
                    ("geojson", "Geojson"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
