# Generated by Django 4.1 on 2023-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_building_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="plus_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
