# Generated by Django 4.1 on 2023-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_building_plus_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vectorlayer",
            old_name="title",
            new_name="description_en",
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base_line_data", "Base Line Data"),
                    ("resource_data", "Resources Data"),
                    ("tourism_data", "Tourism Data"),
                    ("utilities_data", "Utilities Data"),
                    ("open_space", "Open Space"),
                    ("orthophoto", "Orthophoto"),
                    ("raster_data", "Raster Data"),
                    ("risk_and_hazard_data", "Risk and Hazard Data"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="data_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("art_history_and_culture", "Art, History and Culture"),
                    ("basemaps", "Basemaps"),
                    ("blue_infrastructures", "Blue Infrastructures"),
                    ("boundary", "Boundary"),
                    ("disaster", "Diaster"),
                    ("economy", "Economy"),
                    ("education", "Education"),
                    ("economy", "Economy"),
                    ("education", "Education"),
                    ("geography", "Geography"),
                    ("government_bodies", "Government Bodies"),
                    ("health", "Health"),
                    ("organizations", "Organizations"),
                    ("infrastructure", "Infrastructure"),
                    ("industries_and_factories", "Industries and Factories"),
                    ("power_and_energy", "Power and Energy"),
                    ("public_utilities", "Public Utilities"),
                    ("raster", "Raster"),
                    ("recreational_infrastructure", "Recreational Infrastructure"),
                    ("risk_and_hazard", "Risk and Hazard"),
                    ("risk_infrastructure", "Risk Infrastructure"),
                    ("telecommunication", "Telecommunication"),
                    ("tourism_destination", "Tourism Destination"),
                    ("tourism_facilities", "Tourism Facilities"),
                    ("transport", "Transport"),
                    ("water_infrastructure", "Water Infrastructure"),
                    ("agriculture_and_livestock", "Agriculture and Livestock"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="data_source",
            field=models.CharField(
                blank=True,
                choices=[("spatial", "Spatial"), ("non_spatial", "Non Spatial")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="description_ne",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="display_name_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="display_name_ne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="is_boundary_data",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="is_downloadable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="is_open_space_layer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="is_there_metadata",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vectorlayer",
            name="layer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
