# Generated by Django 4.1 on 2023-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_rasterlayer_rasterlayermetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_sp_use",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hospitality", "Hospitality"),
                    ("smes", "SMES"),
                    ("retails", "Retails"),
                    ("construction_and_engineering", "Construction and Engineering"),
                    ("agriculture", "Agriculture"),
                    ("pharmacy", "Pharmacy"),
                    ("entertainment", "Entertainment"),
                    ("financial", "Financial"),
                    ("healthcare", "Healthcare"),
                    ("education", "Education"),
                    ("industry_and_manufacturing", "Industry and Manufacturing"),
                    ("media", "Media"),
                    ("religious", "Religious"),
                    ("mall", "Mall"),
                    ("residential", "Residential"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="plinth_area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="remarks",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="road_lane",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alley", "Alley"),
                    ("single_lane", "Single lane"),
                    ("double_lane", "Double lane"),
                    ("four_lane", "Four lane"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black_topped", "Black Topped"),
                    ("gravel", "Gravel"),
                    ("concrete", "Concrete"),
                    ("earthen", "Earthen"),
                    ("unpaved", "Unpaved"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="road_width",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("registered_and_completed", "Registered and completed"),
                    (
                        "registered_and_under_construction",
                        "Registered and under construction",
                    ),
                    ("not_registered", "Not registered"),
                    ("not_aware", "Not aware"),
                    ("archived", "Archived"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "RCC"),
                    ("tile", "Tile"),
                    ("cgi-sheet", "CGI sheet"),
                    ("straw", "Straw"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rasterlayer",
            name="sld_file",
            field=models.FileField(
                blank=True, null=True, upload_to="raster/sld_uploads"
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("black_topped", "Black Topped"),
                    ("gravel", "Gravel"),
                    ("concrete", "Concrete"),
                    ("earthen", "Earthen"),
                    ("unpaved", "Unpaved"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
