# Generated by Django 4.1 on 2023-08-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_building_building_sp_use_building_plinth_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rcc", "RCC"),
                    ("tile", "Tile"),
                    ("cgi_sheet", "CGI sheet"),
                    ("straw", "Straw"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
