# Generated by Django 4.1 on 2023-08-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_building_building_use"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingCategoryChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(blank=True, max_length=100, null=True)),
                ("name_ne", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="building",
            name="owner_status",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
    ]
