# Generated by Django 4.1 on 2023-08-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_buildingcategorychoice_alter_building_owner_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingcategorychoice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("owner_status", "owner_status")],
                max_length=100,
                null=True,
            ),
        ),
    ]
