# Generated by Django 4.1 on 2023-08-09 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_buildingcategorychoice_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildingcategorychoice",
            old_name="name_en",
            new_name="alias_name",
        ),
        migrations.RenameField(
            model_name="buildingcategorychoice",
            old_name="name_ne",
            new_name="attribute_name",
        ),
    ]
