# Generated by Django 4.1 on 2023-08-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_rename_name_en_buildingcategorychoice_alias_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_image", models.ImageField(upload_to="Files/images")),
                ("building_plan", models.ImageField(upload_to="Files/images")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.building",
                    ),
                ),
            ],
        ),
    ]
