# Generated by Django 4.1 on 2023-08-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="association_type",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="roof_type",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="temprorary_type",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="buildingcategorychoice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner_status", "owner_status"),
                    ("temprorary_type", "temprorary_type"),
                    ("association_type", "association_type"),
                    ("roof_type", "roof_type"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
