# Generated by Django 4.1 on 2023-08-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_building_association_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "attribute_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="building",
            name="building_sp_use",
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_structure",
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_use",
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="reg_type",
            field=models.CharField(
                blank=True,
                choices=[],
                max_length=50,
                null=True,
                verbose_name="registration type",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="road_lane",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="road_type",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="buildingcategorychoice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner_status", "owner_status"),
                    ("temprorary_type", "temprorary_type"),
                    ("association_type", "association_type"),
                    ("roof_type", "roof_type"),
                    ("building_structure", "building_structure"),
                    ("reg_type", "reg_type"),
                    ("building_use", "building_use"),
                    ("building_sp_use", "building_sp_use"),
                    ("road_type", "road_type"),
                    ("road_lane", "road_lane"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_type",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
    ]
