# Generated by Django 4.1 on 2023-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_roadcategory_alter_building_building_sp_use_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadCategoryChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "attribute_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("road_type", "road_type"),
                            ("road_category", "road_category"),
                            ("road_class", "road_class"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RoadCategory",
        ),
        migrations.AlterField(
            model_name="road",
            name="road_category",
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="road",
            name="road_class",
            field=models.CharField(blank=True, choices=[], max_length=30, null=True),
        ),
    ]
