# Generated by Django 4.1 on 2023-08-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_roadcategorychoice_delete_roadcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadcategorychoice",
            name="alias_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="roadcategorychoice",
            name="attribute_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
