# Generated by Django 4.1 on 2023-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_remove_road_ward_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="ward_no",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
