# Generated by Django 4.1 on 2023-08-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_road_ward_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalinstallation",
            name="planned",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="physicalinstallation",
            name="planned_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="physicalinstallation",
            name="updated_date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
