# Generated by Django 4.1 on 2023-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_physicalinstallation_planned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalinstallation",
            name="eta",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
