# Generated by Django 4.1 on 2023-08-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_physicalinstallation_eta"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="associate_road_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
