# Generated by Django 4.1 on 2023-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_building_associate_road_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="road_lane",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
