# Generated by Django 4.1 on 2023-08-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_road_road_lane"),
    ]

    operations = [
        migrations.AddField(
            model_name="road",
            name="direction",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="remarks",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="road_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="road_width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
