# Generated by Django 4.1 on 2023-08-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_road_direction_road_remarks_road_road_length_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_image", models.ImageField(upload_to="Files/images")),
            ],
        ),
        migrations.CreateModel(
            name="BuildingPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_plan", models.ImageField(upload_to="Files/images")),
            ],
        ),
        migrations.RemoveField(
            model_name="building",
            name="building_plan",
        ),
        migrations.AlterField(
            model_name="building",
            name="road_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddField(
            model_name="buildingplan",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_plan",
                to="core.building",
            ),
        ),
        migrations.AddField(
            model_name="buildingimage",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_image",
                to="core.building",
            ),
        ),
    ]
