# Generated by Django 4.1 on 2023-08-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_buildingimage_buildingplan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_image", models.ImageField(upload_to="Files/images")),
                ("building_plan", models.ImageField(upload_to="Files/images")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.building",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="buildingplan",
            name="building",
        ),
        migrations.AlterField(
            model_name="roadcategorychoice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("road_type", "road_type"),
                    ("road_category", "road_category"),
                    ("road_class", "road_class"),
                    ("road_lane", "road_lane"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="BuildingImage",
        ),
        migrations.DeleteModel(
            name="BuildingPlan",
        ),
    ]
