# Generated by Django 4.1 on 2023-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_image_remove_buildingplan_building_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="building_image",
            field=models.ImageField(blank=True, null=True, upload_to="Files/images"),
        ),
        migrations.AlterField(
            model_name="image",
            name="building_plan",
            field=models.ImageField(blank=True, null=True, upload_to="Files/images"),
        ),
    ]
