# Generated by Django 4.1 on 2023-08-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_image_building_image_alter_image_building_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="road_lane",
            field=models.CharField(blank=True, choices=[], max_length=30, null=True),
        ),
    ]
