# Generated by Django 4.1 on 2023-08-23 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_road_road_lane"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="temprorary_type",
            new_name="temporary_type",
        ),
    ]
