# Generated by Django 4.1 on 2023-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_rename_temprorary_type_building_temporary_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingcategorychoice",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("owner_status", "owner_status"),
                    ("temporary_type", "temporary_type"),
                    ("association_type", "association_type"),
                    ("roof_type", "roof_type"),
                    ("building_structure", "building_structure"),
                    ("reg_type", "reg_type"),
                    ("building_use", "building_use"),
                    ("building_sp_use", "building_sp_use"),
                    ("road_type", "road_type"),
                    ("road_lane", "road_lane"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
