# Generated by Django 4.1 on 2023-09-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="house_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
