# Generated by Django 4.1 on 2023-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_alter_building_building_sp_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorlayer",
            name="default_load",
            field=models.BooleanField(default=False),
        ),
    ]
