# Generated by Django 4.1 on 2023-09-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_vectorlayer_default_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
