# Generated by Django 4.1 on 2023-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_building_building_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="main_building_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
