# Generated by Django 4.1 on 2023-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_building_main_building_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingcategorychoice",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
