# Generated by Django 4.1 on 2023-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_buildingcategorychoice_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingcategorychoice",
            name="order",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
