# Generated by Django 4.1 on 2023-10-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_alter_buildingcategorychoice_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadcategorychoice",
            name="order",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
