# Generated by Django 4.1 on 2023-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_buildinggeometry_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="ward_no_informal",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
