# Generated by Django 4.1 on 2023-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_roadgeometry_created_by_roadgeometry_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadgeometry",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
