# Generated by Django 4.1 on 2023-12-28 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_roadgeometry_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historylog",
            name="timestamp",
        ),
    ]
