# Generated by Django 4.1 on 2023-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_remove_historylog_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buildinggeometry",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historylog",
            name="related_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historylog",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadgeometry",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
