# Generated by Django 4.1 on 2023-12-28 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_building_timestamp_buildinggeometry_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="ref_centroid",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
