# Generated by Django 4.1 on 2024-01-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_historylog_association_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingcategorychoice",
            name="alias_name_ne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roadcategorychoice",
            name="alias_name_ne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="roadcategorychoice",
            name="alias_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="roadcategorychoice",
            name="attribute_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
