# Generated by Django 4.1 on 2023-10-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0002_rename_benifit_card_benefit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("title_ne", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="about",
            name="file_data",
        ),
        migrations.AddField(
            model_name="about",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="use_case_major_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_card",
                to="dmaps.usecasemajorfeature",
            ),
        ),
    ]
