# Generated by Django 4.1 on 2023-10-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0003_collaborations_remove_about_file_data_about_file_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "major_feature_images",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="major_feature_images",
                        to="dmaps.card",
                    ),
                ),
            ],
        ),
    ]
