# Generated by Django 4.1 on 2023-10-13 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0004_images"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Images",
            new_name="Image",
        ),
    ]
