# Generated by Django 4.1 on 2023-10-16 07:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dmaps", "0005_rename_images_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="benefit",
            new_name="benefit_en",
        ),
        migrations.RemoveField(
            model_name="card",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="card",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="card",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="card",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="card",
            name="benefit_ne",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="collaboration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration_card",
                to="dmaps.collaborations",
            ),
        ),
        migrations.AddField(
            model_name="collaborations",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborations",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collaborations",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborations",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="usecase",
            name="use_case",
            field=models.CharField(
                blank=True,
                choices=[
                    ("municipal_management", "Municipal Management"),
                    ("navigational_operations", "Navigational Operations"),
                    (
                        "data_management_and_centralization",
                        "Data Management and Centralization",
                    ),
                    (
                        "geospatial_planning_and_visualization",
                        "Geospatial Planning and Visualization",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="NavBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("title_ne", models.CharField(blank=True, max_length=500, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons/")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Intro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("title_ne", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_ne",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "collaborator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("supporter", "Supporter"),
                            ("mapping_partner", "Mapping Partner"),
                            ("implementing_partner", " Implementing Partner"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("phone_no", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title_en", models.CharField(blank=True, max_length=200, null=True)),
                ("title_ne", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
