# Generated by Django 4.1 on 2023-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0006_rename_benefit_card_benefit_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="collaboration",
        ),
        migrations.RemoveField(
            model_name="card",
            name="contact_us",
        ),
        migrations.RemoveField(
            model_name="card",
            name="major_component",
        ),
        migrations.RemoveField(
            model_name="card",
            name="major_feature",
        ),
        migrations.RemoveField(
            model_name="card",
            name="use_case",
        ),
        migrations.RemoveField(
            model_name="card",
            name="use_case_major_feature",
        ),
        migrations.RemoveField(
            model_name="card",
            name="we_work_with",
        ),
        migrations.AddField(
            model_name="card",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("major_feature", "Major Feature"),
                    ("major_component", "Major Component Case"),
                    ("we_work_with", "We Work With"),
                    ("contact_us", "Contact Us"),
                    ("use_case", "Use Case"),
                    ("use_case_major_feature", "Use Case Major Feature"),
                    ("collaboration", "Collaboration"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
