# Generated by Django 4.1 on 2023-10-18 05:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0009_alter_card_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeometryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("municipality", "Municipality"),
                            ("province", "Province"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("file_upload", models.FileField(upload_to="maps")),
            ],
        ),
        migrations.CreateModel(
            name="MunicipalityGeometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.FloatField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvinceGeometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.FloatField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
