# Generated by Django 4.1 on 2023-10-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0010_geometryfile_municipalitygeometry_provincegeometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipalitygeometry",
            name="attr_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="municipalitygeometry",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="provincegeometry",
            name="attr_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="provincegeometry",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
