# Generated by Django 4.1 on 2023-11-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0011_municipalitygeometry_attr_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("title_ne", models.CharField(blank=True, max_length=500, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ne", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
