# Generated by Django 4.1 on 2023-11-23 08:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0012_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=500, null=True)),
                ("title_ne", models.CharField(blank=True, max_length=500, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ne", models.TextField(blank=True, null=True)),
                (
                    "use_case_card",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="use_case_sdg",
                        to="dmaps.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UseCaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_en", models.CharField(blank=True, max_length=500, null=True)),
                ("topic_ne", models.CharField(blank=True, max_length=500, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("area_en", models.CharField(blank=True, max_length=500, null=True)),
                ("area_ne", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "task_completed_en",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "task_completed_ne",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "use_case_card",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="use_case_detail",
                        to="dmaps.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SDGImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sdg_images",
                    models.ImageField(blank=True, null=True, upload_to="sdg_images/"),
                ),
                (
                    "sdg_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdg_data",
                        to="dmaps.sdg",
                    ),
                ),
            ],
        ),
    ]
