# Generated by Django 4.1 on 2023-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0013_sdg_usecasedetail_sdgimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usecasedetail",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="usecasedetail",
            name="start_date",
        ),
        migrations.AddField(
            model_name="usecasedetail",
            name="funding_agency_en",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="usecasedetail",
            name="funding_agency_np",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
