# Generated by Django 4.1 on 2023-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0014_remove_usecasedetail_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecasedetail",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usecasedetail",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
