# Generated by Django 4.1 on 2023-11-28 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0015_usecasedetail_end_date_usecasedetail_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="about",
            name="title_ne",
        ),
        migrations.RemoveField(
            model_name="header",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="header",
            name="title_ne",
        ),
    ]
