# Generated by Django 4.1 on 2023-11-28 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dmaps", "0016_remove_about_title_en_remove_about_title_ne_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="title_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="about",
            name="title_ne",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="header",
            name="title_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="header",
            name="title_ne",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
