# Generated by Django 4.1 on 2023-09-12 07:50

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Male",
                        max_length=15,
                    ),
                ),
                ("ward", models.JSONField(blank=True, default=list, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="upload/profile/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="upload/profile/",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserGroup",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("change_user_status", "Can change the status of the user"),
                    ("has_ward_filter", "Has ward filter option"),
                ],
            },
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
