# Generated by Django 4.1 on 2023-09-13 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("change_user_status", "Can change the status of the user"),
                    ("view_user_management", "Can view user management"),
                    ("edit_user_management", "Can edit user management"),
                    ("view_visualization", "Can view visualization page"),
                    ("edit_visualization", "Can edit visualization page"),
                    ("view_layer_attribute", "Can view layer attribute page"),
                    ("edit_layer_attribute", "Can edit layer attribute page"),
                    ("view_data_management", "Can view data management page"),
                    ("edit_data_management", "Can edit data management page"),
                ]
            },
        ),
    ]
