# Generated by Django 4.1 on 2023-11-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_workshopmode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopmode",
            name="workshop_mode",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
